language: generic

git:
  depth: 10

env:
  global:
  - PROG_VER=$(cat VERSION.txt)

matrix:
  include:

    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
      - task=1-stretch
      addons:
        apt:
          packages:
          - jq
          - qemu-user-static
      script:
      - docker run --rm -v "${PWD}:/transgui" -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static resin/raspberry-pi-debian:stretch bash -c "sed -i 's/archive.raspbian.org/mirrors.ocf.berkeley.edu\/raspbian/g' /etc/apt/sources.list && cd /transgui/setup/unix/ && ./debian-ubuntu-install_deps.sh && ./build.sh"
      deploy:
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./Release/transgui-$PROG_VER-armv6l-Linux.txz
        skip_cleanup: true
        on:
          tags: true


    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
      - task=2-stretch
      addons:
        apt:
          packages:
          - jq
          - qemu-user-static
      script:
      - docker run --rm -v "${PWD}:/transgui" -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static resin/raspberry-pi2-debian:stretch bash -c "sed -i 's/archive.raspbian.org/mirrors.ocf.berkeley.edu\/raspbian/g' /etc/apt/sources.list && cd /transgui/setup/unix/ && ./debian-ubuntu-install_deps.sh && ./build.sh"
      deploy:
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./Release/transgui-$PROG_VER-armv7l-Linux.txz
        skip_cleanup: true
        on:
          tags: true

    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
      - task=2-jessie
      addons:
        apt:
          packages:
          - jq
          - qemu-user-static
      script:
      - docker run --rm -v "${PWD}:/transgui" -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static resin/raspberry-pi2-debian:jessie bash -c "sed -i 's/archive.raspbian.org/mirrors.ocf.berkeley.edu\/raspbian/g' /etc/apt/sources.list && cd /transgui/setup/unix/ && ./debian-ubuntu-install_deps.sh && ./build.sh"
      deploy:
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./Release/transgui-$PROG_VER-armv7l-Linux.txz
        skip_cleanup: true
        on:
          tags: true

    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
      - task=3-jessie
      addons:
        apt:
          packages:
          - jq
          - qemu-user-static
      script:
      - docker run --rm -v "${PWD}:/transgui" -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static resin/raspberry-pi3-debian:jessie bash -c "sed -i 's/archive.raspbian.org/mirrors.ocf.berkeley.edu\/raspbian/g' /etc/apt/sources.list && cd /transgui/setup/unix/ && ./debian-ubuntu-install_deps.sh && ./build.sh"
      deploy:
      - provider: releases
        api_key:
          secure: XfbJq1d1kstUAGoaW9NeiOOufiu/hsWgQONnTdf2fDESZSOAMR11x8bnsySlywDh2qwO3/GC1RbgTY/7ZXuzzm4vJgtl+dcxtclh4qi+hNEEkUpPWWaY0ov+45s6eR/B9H4R+7tm4ISiVgK6cgOrQQhI0AePh5/sJLBR5yVfCM9mDIoaNj0oES+oTjRixnk8srbLga6rH47xrkVTnQhWuUTQnfse1r1JgiN92lbZ1gVQGeOGdbuhztU8rcIMQEj+Nu/ub6hglf/zIPzA5D2sZnUNhURoPAb27eqWX7bXrliEXhhpCX7KTAe/wEkjtOb8LCEuSSahEAvYTXbfOBpe8AZb5tXzg2mxv0dEJLfInoSDhtZVeEBtS+q4BwVT8xLgVfRdAOUFBoKhgcayP1gL//VS1fvGEUiSh0KykDTOBBZOPfN7uu8x2nX/AZmEuwojaQ6r0UY2q1gD1d4zpfLlqCz8+RFuT9BQ9vfVdHAeO3VnDbTTQjUQNVNrDmp5yJ2b721BMXrehlqvjPoDQCPgRbxeWik4jcJKMVi3GGultCj7wmtFhuWYTf9LpSygPivBTlJggndpx8UWC/N19h/tJb2ULdVQtrmuWjs5168psQi2Eh0yjAwRQPQ3Hj5ZK9CrRy7Pic4+wh2cOjoCV1N2N5+Ky5CHyjQ8wZY4U3auAxI=
        file: ./Release/transgui-$PROG_VER-armv7l-Linux.txz
        skip_cleanup: true
        on:
          tags: true

notifications:
  email:
    on_failure: true
